apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ytsaurus-ui-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
     {{- include "ytsaurus-ui-chart.labels" . | nindent 4 }}
data:
  clusters-config.json: |
    {{ .Values.ui.clusterConfig | toJson }}
  common.js: |
    module.exports = {
      odinBaseUrl: {{ .Values.settings.odinBaseUrl | quote }},
      uiSettings: {
        directDownload: {{ .Values.settings.directDownload | toJson }},
        uploadTableExcelBaseUrl: {{ .Values.settings.uploadTableExcelBaseUrl | quote }},
        exportTableBaseUrl: {{ .Values.settings.exportTableBaseUrl | quote }},
        accessLogBasePath: {{ .Values.settings.accessLogBasePath | quote }},
      },
      {{- if .Values.settings.oauth.enabled }}
      ytOAuthSettings: {
        baseURL: {{ .Values.settings.oauth.baseURL | quote }},
        authPath: {{ .Values.settings.oauth.authPath | quote }},
        logoutPath: {{ .Values.settings.oauth.logoutPath | quote }},
        tokenPath: {{ .Values.settings.oauth.tokenPath | quote }},
        clientId: process.env.{{ .Values.settings.oauth.clientIdEnvName }},
        clientSecret: process.env.{{ .Values.settings.oauth.clientSecretEnvName }},
        scope: {{ .Values.settings.oauth.scope | quote }},
        buttonLabel: {{ .Values.settings.oauth.buttonLabel | quote }},
      },
      }
      {{- else -}}
      }
      {{- end -}}
