name: "[manual]: Docker build"

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: Prefix of tag
        default: dev
        required: true
      ref:
        description: "Checkout branch (suffix of tag)"
        required: true
      override:
        description: "Allow override tag"
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: npm ci
        run: |
          npm ci

      - name: "Docker: build & push"
        run: |
          cd packages/ui

          UI_IMAGE=$( npm run -s show:docker-image-name )
          UI_TAG=$( echo "${{ inputs.prefix }}-${{ inputs.ref }}" | sed -E 's/\W/-/g' )

          TARGET_IMAGE=${UI_IMAGE}:${UI_TAG}
          echo target image and tag: ${TARGET_IMAGE}

          if ( test "true" = "${{ inputs.override }}" || ! docker pull ${TARGET_IMAGE} ) ; then
            npm run docker:build --dockertag=${UI_TAG}
            echo '${{ secrets.GITHUB_TOKEN }}' | docker login --username ${{ github.actor }} --password-stdin ghcr.io
            npm run docker:push --dockertag=${UI_TAG}
          else 
            echo Corresponding image already exists: $TARGET_IMAGE
          fi
